name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r ml/requirements.txt

      - name: Run tests
        run: |
          pytest tests/backend
          pytest tests/ml

      - name: Lint code
        run: |
          pip install flake8
          flake8 backend app ml scripts

      - name: Build Docker images
        run: |
          docker-compose -f infra/docker-compose.yml build

      - name: Push Docker images
        run: |
          docker-compose -f infra/docker-compose.yml push